name: Web Syntax Check Pipeline

on:
  pull_request:
    branches: [ "main" ]

jobs:
  syntax-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Syntax Checkers (Linters)
        run: npm install -g jshint htmlhint

      - name: Check JavaScript Syntax
        run: jshint "ESTI/**/*.js"

      - name: Check HTML Syntax
        run: htmlhint "ESTI/**/*.html" --ignore "**/index.html"